config/routes.rb
Rails.application.routes.draw do
  get 'items/create'

  devise_for :users

  resources :users, only: [:show] do
    resource :items, only: [:create, :destroy]
  end

  get 'about' => 'welcome#about'
  get 'blocitoff' => 'welcome#index'
  get 'users/show' => 'users#show'
  root 'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :name, length: { minimum: 1 }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :except => [:index, :about]

  def after_sign_in_path_for(resource_or_scope)
    current_user
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private
  def after_confirmation_path_for(resource_name, resource)
    sign_in(resource) # In case you want to sign in the user
    your_new_after_confirmation_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @item = @user.items.new(item_params)

    if @item.save
      flash[:notice] = "To-Do item: \"#{@item.name.capitalize}\" was saved successfully! :)"
      redirect_to user_path(:id)
    else
      flash[:alert] = "There was an error saving your item.  Please try again."
      redirect_to user_path(:id)
    end

    # respond_to do |format|
    #   format.html { redirect_to user_path(:id) }
    #   format.js
    # end
  end

  def destroy
    @user = User.find(params[:user_id])
    @item = Item.find(params[:format])

    if @item.destroy
      flash.now[:notice] = "Item: \"#{@item.name.capitalize}\" is complete!"
      redirect_to user_path(:id)
    else
      flash.now[:alert] = "There was an error marking off this item."
      redirect_to user_path(:id)
    end

    # respond_to do |format|
    #   format.html { redirect_to user_path(:id) }
    #   format.js
    # end
  end

  private

  def item_params
    params.require(:item).permit(:name, :user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @items = @user.items.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper

  def days_left(item)
    distance_of_time_in_words(Time.now, item.created_at + 7.days)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<h4>Add a To-Do List Item</h4>
<%= form_for [user, item] do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter a new item here: ", autofocus: true %>
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Item #</th>
      <th >Item Name</th>
      <th>Remove Item</tH>
      <th>Days left to complete</th>
    </tr>
  </thead>
  <tbody>
    <% @user.items.each do |item| %>
    <tr>
      <td class="count"></td>
      <td id="item-<%= item.id%>"><%= item.name.capitalize %></td>
      <td> <%= link_to "", user_items_path(item.user, item.id), method: :delete, class: 'glyphicon glyphicon-ok' %></td>
      <td><%= days_left(item) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.js.erb
$("#item-<%= @item.id %>").hide();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>BlocitoffBe</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocitoff", blocitoff_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "To-Do's", users_show_path %></li>
        <div class="pull-right user-info">
          <% if user_signed_in? %>
            Signed in as:<strong><%= current_user.email %></strong> |
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> -
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
          <% else %>
            <%= link_to 'Sign_in', new_user_session_path, :class => 'navbar-link' %> or
            <%= link_to 'Sign_up', new_user_registration_path, :class => 'navbar-link' %>
          <% end %>
        </div>
      </ul>
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= current_user.email %></h1>
<div class="container-fluid">
  <h3>Your To-Do List:</h3>
    <div class="row">
      <%= render '/items/item', locals: { user: @user } %>
    </div>
  <%= render '/items/form', item: Item.new, user: @user %>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div>
  <h1 class="text-center"> Welcome! </h1>
  <h3 class="text-center">Your to do list will be visible here shortly.</h3>
</div>